// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2lglK3bWi12Tso6CHpq6PzuqbUTQ8BS4',
    appId: '1:278704044549:web:e7d3de154a700630c8ba6c',
    messagingSenderId: '278704044549',
    projectId: 'menorton-test-integration',
    authDomain: 'menorton-test-integration.firebaseapp.com',
    storageBucket: 'menorton-test-integration.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGc0FN2GjtHa_gmG5tDImhgXcoNLbFW-U',
    appId: '1:278704044549:android:ab6747ee7579f020c8ba6c',
    messagingSenderId: '278704044549',
    projectId: 'menorton-test-integration',
    storageBucket: 'menorton-test-integration.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwXznkgxok001LrIacij_r2lD9gGyMe1w',
    appId: '1:278704044549:ios:390ad9704020410ec8ba6c',
    messagingSenderId: '278704044549',
    projectId: 'menorton-test-integration',
    storageBucket: 'menorton-test-integration.appspot.com',
    iosBundleId: 'com.example.namerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwXznkgxok001LrIacij_r2lD9gGyMe1w',
    appId: '1:278704044549:ios:390ad9704020410ec8ba6c',
    messagingSenderId: '278704044549',
    projectId: 'menorton-test-integration',
    storageBucket: 'menorton-test-integration.appspot.com',
    iosBundleId: 'com.example.namerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2lglK3bWi12Tso6CHpq6PzuqbUTQ8BS4',
    appId: '1:278704044549:web:df48dc69e6c02fcec8ba6c',
    messagingSenderId: '278704044549',
    projectId: 'menorton-test-integration',
    authDomain: 'menorton-test-integration.firebaseapp.com',
    storageBucket: 'menorton-test-integration.appspot.com',
  );
}
